/**
 * Error codes returned by the backend API.
 * Used for mapping API errors to user-friendly messages in handleApiError.
 */

export enum OnboardingErrorCodes {
  PENDING_ONBOARDING_EXISTS = "PENDING_ONBOARDING_EXISTS",
  DRAFT_ONBOARDING_EXISTS = "DRAFT_ONBOARDING_EXISTS",
  ACTIVE_ONBOARDING_EXISTS = "ACTIVE_ONBOARDING_EXISTS",
  ONBOARDING_NOT_FOUND = "ONBOARDING_NOT_FOUND",
  /** Comprehensive onboarding submit with missing compulsory documents */
  MISSING_ONBOARDING_DOCUMENTS = "MISSING_ONBOARDING_DOCUMENTS",
}

export enum RequirementListErrorCodes {
  DUPLICATE_DOCUMENT_TYPE_IDS = "DUPLICATE_DOCUMENT_TYPE_IDS",
  DOCUMENT_TYPE_ASSOCIATION_FAILED = "DOCUMENT_TYPE_ASSOCIATION_FAILED",
  DOCUMENT_TYPE_ASSOCIATION_UPDATE_FAILED = "DOCUMENT_TYPE_ASSOCIATION_UPDATE_FAILED",
}

/** Multi-document types / application requirement error codes */
export enum ApplicationRequirementErrorCodes {
  DOCUMENT_TYPE_REQUIRED = "DOCUMENT_TYPE_REQUIRED",
  MISSING_DOCUMENT = "MISSING_DOCUMENT",
  REQUIREMENT_CREATION_FAILED = "REQUIREMENT_CREATION_FAILED",
}
